music_generator:
  model: "facebook/musicgen-small"
  input_type: "text"
  output_dir: "generated_audio"
  exp_name: "default"

riffusion_pipeline:
  input_type: "text"
  output_dir: "generated_audio"
  exp_name: "riffusion_text"
  inference_steps: 1

# Experiment 1
