language:
  python

# 2.7 doesn't work with nnAudio
# 3.8 and 3.9 don't work with openl3 old-school TF
matrix:
  include:
    - os: linux
      dist: focal
      python: 3.6
    - os: linux
      dist: focal
      python: 3.7
    - os: linux
      dist: bionic
      python: 3.6
    - os: linux
      dist: bionic
      python: 3.7
    - os: linux
      dist: groovy
      python: 3.6
    - os: linux
      dist: groovy
      python: 3.7
    # https://travis-ci.community/t/how-to-skip-python-download-to-osx-image-and-avoid-download-unavailable-error/9554/2
    #- os: osx
    #  # Would be nice to try different python versions :(
    #  #python: 3.7
    #  osx_image: xcode10.2
    #- os: osx
    #  # Would be nice to try different python versions :(
    #  #python: 3.7
    #  osx_image: xcode12.4

before_install:
  - sudo apt-get install -y libsndfile1 libsndfile-dev libhdf5-dev python3-h5py
  - python --version
  - pip install -U pip
  - pip install -U pytest
install:
  - pip install "Cython>=0.23.4"    # scikit-image needs this installed first
  - pip install ".[test]" . # install package + test dependencies
script:
  - pytest
after_success:
  - bash <(curl -s https://codecov.io/bash)
